### ISSUE TITLE
Oscar Roadmap

### ISSUE THREAD

**Issue by wbhart** [oscar-system/Oscar.jl#1]
This is a roadmap of all issues people consider important or of high priority across the whole of the Oscar system.
Names are attached to the issues currently being worked on. They are in no particular order.

- Infrastructure
  - [X] Report type inference issues to Julia - @wbhart
  - [X] Continuous integration - @rbehrends 
  - [x] Flint release, roadmap : https://github.com/wbhart/flint2/issues/517 - @wbhart 
  - [X] Julia testsets @rfourquet @wbhart
- AbstractAlgebra.jl, Nemo
  - [X] Modules over Euclidean domains - @wbhart 
  - [ ] iseuclidean, isdomain, etc. predicates in AbstractAlgebra
  - [ ] clean up left/right kernel/solve interface in AbstractAlgebra @a-kulkarn
  - [ ] Groups interface - @kalmarek @fieker @fingolfin 
  - [ ] Interface conformance testing
  - [ ] Wrap Flint's fq_zech modules
  - [ ] Embeddings of finite fields @wbhart @erou
   - [ ] Expansion of a rational function as a Laurent series
   - [ ] Better user documentation and test code for Nemo.jl @wbhart
   - [ ] Clean up and merge a-kulkarn's work on solve (includes making the same improvements to Nemo as he has made to AbstractAlgebra) https://github.com/Nemocas/AbstractAlgebra.jl/pull/559
- Hecke.jl
   - [ ] Rational functions over cyclotomic fields (requested by Frank and Thomas) - @wbhart @fieker  @tthsqe12
   - [X] Fix Euclidean division functions (div, rem, divrem) https://github.com/Nemocas/Nemo.jl/issues/699
   - [X] Localisations of Z and K[x] @fieker
  - [X] Finitely generated abelian groups - @fieker 
- Singular, Singular.jl
  - [X] Nemo coefficient rings in Singular.jl @sebasguts @wbhart
  - [X] Get tests passing on OSX @wbhart
  - [X] BinaryProvider for Singular.jl @wbhart @thofma @hannes14 
  - [X] Make Singular.jl an official Julia package @wbhart
  - [X] Remove execute from Singular library code - @steenpass @hannes14 (+HiWi)
  - [X] Parallel conversion of Singular multivariates to Factory and vice versa - @hannes14 
  - [X] Integrate Flint multivariates into Factory (ODK) - @hannes14 @tthsqe12
  - [X] Subquotient modules for Singular.jl @fieker 
  - [X] Singular to Julia transpiler - @hannes14 @tthsqe12 @rfourquet
  - [X] Access to Singular interpreter/libraries from Singular.jl - https://github.com/oscar-system/Singular.jl/pull/104 - @sebasguts @wbhart
  - [X] Fix off by one error in resolutions @wbhart @hannes14 
  - [x] Wrap more Singular kernel functions in Singular.jl
  - [X] Automatically build documentation on GitHub pages @wbhart
  - [ ] Wrap plural
   - [x] Fix Euclidean division functions (div, rem, divrem) https://github.com/Nemocas/Nemo.jl/issues/699
- GAP, GAP.jl
  - [X] BinaryProvider for GAP.jl @fingolfin 
  - [x] High level interface for GAP.jl
  - [x] GAP help available in Julia - https://github.com/oscar-system/GAP.jl/pull/251 - @ThomasBreuer @sebasguts
  - [x] GAP REPL mode - https://github.com/oscar-system/GAP.jl/pull/225 - @sebasguts 
- Polymake, Polymayke.jl
  - [x] High level interface for Polytopes: [OscarPolytope.jl](https://github.com/oscar-system/OscarPolytope.jl) @lkastner 
  - [X] Polymake.jl on OSX @benlorenz 
- Oscar.jl
  - [x] User documentation for Oscar.jl
  - [ ] Conversion functions between different matrix and polynomial types in Oscar.jl
  - [X] Refresh Oscar repository - @wbhart 
  - [ ] Import of chosen default functionality into Oscar.jl from other systems
      - This does not mean "using Hecke; using Nemo; using Singular", etc. It means importing only the required functionality, as the former is not expected to be possible.
- Unsorted
  - [X] Harmonise interface for Fin Gen Ab Gps and Fin Pres Mods over Euc Dom - @fieker @wbhart 
  - [ ] Euc. domain interface, esp. for polys and matrices in AbstractAlgebra - @wbhart @fieker 
  - [ ] Precompile some code for basic rings (e.g. Z, Z/pZ, Q, etc.) to avoid Jit overhead
  - [X] Implement Julia map functionality for our types @rfourquet
  - [x] Decorated rings/modules (gradings, etc.) @fieker

**Comment by kalmarek** [comment]
Ring interface conformance tests:
https://gist.github.com/kalmarek/76b674c63b62c0d02605e7d0c1068f17
(most of our rings I tried fail this)

Group interface + conformance tests:
https://gist.github.com/kalmarek/3ac179c7fbf1190e27f7f335f64520dc
(follows what we did in Kaiserslautern with @fingolfin, @fieker and @ThomasBreuer).

Note, that due to complete lack of time I'm not going to integrate them in the near future, so if you think it's needed before the first release...

**Comment by fieker** [comment]
localisations of Z, K[x] and (maximal) orders of numberfields are availabe though Hecke

**Comment by a-kulkarn** [comment]
Cool! How does it work?

**Comment by fieker** [comment]
On Fri, Sep 04, 2020 at 08:28:09PM -0700, a-kulkarn wrote:
> Cool! How does it work?

I have no idea. I clicked on random things and wasn't even sure it saved
those....

**Comment by fingolfin** [comment]
This has served its purpose, and is otherwise not being referenced by anyone anymore, so closing this now
