### ISSUE TITLE
Release 0.8 todo

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1026]
- [x] New AA release
- [x] New Nemo release
- [x] New Hecke release
- [x] New `libsingular_jll` + `libsingular_julia.jll` (https://github.com/JuliaPackaging/Yggdrasil/pull/4285)
- [x] Resolve #1030
- [x] Ideally also PR #1004 (but that requires a Nemo release first)

Please edit and add other items that should be resolved before the next release.

**Comment by fingolfin** [comment]
Added two items. It would be good if @ThomasBreuer and me could be notified once Nemo has a new release, so that PR #1004 can be updated and hopefully merged (assuming its tests pass; if there are deeper problems, we can punt it to a later Oscar release)
