### ISSUE TITLE
ToricVarieties: Goals for 2023 and beyond (some very long standing goals are listed below)

### ISSUE THREAD

**Issue by HereAround** [oscar-system/Oscar.jl#1834]
# Coherent sheaves (cf. https://github.com/oscar-system/Oscar.jl/pull/1809)

- [ ] Tangent and cotangent bundle of toric varieties.
- [ ] Normal and tangent bundle of complete intersections.
- [ ] Compute resolutions and use cohomCalg to try to compute their cohomologies. (Will of course not always work, but is a quick first check.)
- [ ] Extend to coherent sheaves and their cohomologies (this is the heart of the [ToricVarieties_project](https://github.com/homalg-project/ToricVarieties_project)).
- [ ] Maybe make use of Spectral Sequence of Filtered Topological Space (cc @HechtiDerLachs ) (cf. CLs page 582 ff).
- [ ] Compute Hodge numbers for complete intersections in toric varieties (cf. https://github.com/oscar-system/Oscar.jl/issues/770)

# Migration of other code

## Interesting software in [ToricVarieties_project](https://github.com/homalg-project/ToricVarieties_project)

- [ ] H0Approximator

## Interesting software in Singular

- [ ] `toric.lib`: Create toric ideal from exponent vectors (and compute a standard basis). This could be useful if we want to go from special schemes/varieties, namely those cut out by toric ideals to toric varieties. Benefits are to apply special toric methods (quicker, more powerful) than the generic scheme algorithms.
- [ ] `cisimplicial.lib`: Answers the question if a toric ideal a complete intersection.
- [ ] Possibly rewrite the existing `C` functionality in `julia`. (About 2000 lines of existing Singular code.)

# Completed

- [x] QSMExplorer (part of FTheoryTools by now)
- [x] Class group should return interpretation map (cf. https://github.com/oscar-system/Oscar.jl/issues/1095) for Oscar-wide consolidation.
- [x] Add @ref for `is_trivial` and `is_irreducible` (cf. https://github.com/oscar-system/Oscar.jl/issues/1471)
- [x] Toric blowups at arbitrary codimension. Provide constructor based on coordinate names that specify the blowup center. (https://github.com/oscar-system/Oscar.jl/pull/2228)
- [x] Toric blow-down morphisms for blowups.
- [x] Toric blow-ups which allow do not require a smooth cone/cone contained in smooth cones only.
- [x] Integration of FtheoryTools (https://github.com/Julia-meets-String-Theory/FTheoryTools.jl) (https://github.com/oscar-system/Oscar.jl/pull/2092)
- [x] Toric schemes: More to come, but a beginning has been made (https://github.com/oscar-system/Oscar.jl/pull/1544).
- [x] Function that tells us the ray-coordinate-correspondence: https://github.com/oscar-system/Oscar.jl/pull/2245

**Comment by thofma** [comment]
How about using markdown syntax, e.g. `# heading`?

**Comment by HereAround** [comment]
> How about using markdown syntax, e.g. `# heading`?

Done. Thx for the pointer.

**Comment by HechtiDerLachs** [comment]
> * Tangent and cotangent bundle of toric varieties.

Have a look at #1840, if you like: There, I provide constructors for the (co-)tangent sheaves of arbitrary covered schemes. Through the work in #1636 this will also become available for toric varieties in the scheme theoretic sense. 

However, I'm afraid that this is not precisely what you had in mind. I expect, you were thinking of these sheaves as something with a particular combinatorial description (like toric line bundles?). I would be interested in modeling a special type for these kind of sheaves which knows about their toric descriptions and build the bridge between the two sides. So that we can access different algorithmic backend for these, e.g. for cohomology computations, etc.
