### ISSUE TITLE
Serialization Roadmap

### ISSUE THREAD

**Issue by antonydellavecchia** [oscar-system/Oscar.jl#2406]
This issue describes the roadmap to serialization in OSCAR.  Comments are very welcome.

A proof of concept implementation (for selected types) exists in OSCAR for a while; it builds on a working serialization concept in polymake.  Yet that requires several improvements, which are on their way in  [this branch](https://github.com/oscar-system/Oscar.jl/tree/adv/file-formatting).

Serialization in OSCAR is more complex: for some types the serialization does not only depend on the type. Example: finite fields, which are constructed as a sequence of algebraic extensions over a prime field. Overall, data (in OSCAR) has a tree shape.  An important requirement is a dictionary of parent types; to allow for, e.g.,  coefficients of various polynomials to live in the same ring (or not).

Here are the next steps.

- [x] #2513
- [x] #2514
- [ ] Serialization for groups
- [x] https://github.com/oscar-system/Oscar.jl/issues/1507
- [ ] write a developer's guide to explain how OSCAR developers can serialize their own types
- [ ] implement more advanced types such as, e.g., polynomials whose coefficients live in some matrix algebra
- [ ] demo a second format different from JSON (in memory format?)

@antonydellavecchia oversees all efforts toward serialization.

**Comment by micjoswig** [comment]
FYI: @fingolfin @thofma @lkastner

**Comment by antonydellavecchia** [comment]
The ordering of these issues isn't fixed and is open to discussion. For example it might make sense to have issue #1507 (@fingolfin, @fieker) resolved before serialization for groups (@ThomasBreuer ).

**Comment by benlorenz** [comment]
- [x] Refactor some repeating patterns, see https://github.com/oscar-system/Oscar.jl/pull/2102#discussion_r1252807112
