### ISSUE TITLE
FTheoryTools - Goals for 2024 and beyond

### ISSUE THREAD

**Issue by HereAround** [oscar-system/Oscar.jl#2699]
# To be discussed

# Current WIP

- [ ] Make sure there is documentation for every rng kwarg. Make this uniform in the form of a note?
- [ ] `special_flux_family` has optional kwarg to select the employed algorithm. I suppose it makes sense to propagate this choice to any function that calls `special_flux_family`? How about the random seed? This is only used in case the special algorithm is used. So I suppose this should also be propagated...
- [ ] As an example, look at the following:
```julia
@attr FamilyOfG4Fluxes function g4_flux_family(gf::G4Flux; completeness_check::Bool = true)
  nb = breaks_non_abelian_gauge_group(gf)
  gfs = special_flux_family(model(gf), not_breaking = !nb, completeness_check = completeness_check)
  return gfs
end
```

# Important admin tasks

- [ ] Follow-up submission at https://onlinelibrary.wiley.com/journal/15213978.
- [ ] JHEP or https://www.sigsam.org/cca/index.html?

# Important coding tasks

- [ ] Algorithm selection via symbols, not strings.

### Code optimization

- [ ] The data type of the attributes `weierstrass_model` and `global_tate_model` for a given `hypersurface_model`...
        1. changes its type upon calling said attributes. Before the call, the value is likely (?) a string, afterwards likely (?) a Weierstrass/global Tate model. Is this truly desired? Type stable?
        2. In theory, both the 'Weierstrass and global Tate model should exist for a given hypersurface model. However, in practice this is very different from knowing an exact representation/computing such a representation. As such, we also need to carefully gauge the words to be used in the error message, like "Sorry - we are currently too stupid to compute the Weierstrass/global Tate model, and thus cannot provide details. But in theory, it exists."
- [ ] Kwargs need not be used in doc string refs. Can be removed.
- [ ] Datatypes in FTheoryTools https://github.com/oscar-system/Oscar.jl/issues/4941.
- [ ] `Hypersurface_equation_parametrization` is only supported for hypersurface models. It is a missing feature for Weierstrass and global Tate models. Also, when over a concrete base and the genesis is favorable, it should have a meaningful hypersurface equation parametrization. Is this true? If not, fix it.
- [ ] Increase code coverage of tests.
- [ ] Use macro to generate attribute getters. This should reduce code a lot and be easier to maintain.
- [ ] There will be a framework on parallel computing in OSCAR. Try to make use of it.
- [ ] Tuning - what actions are needed?
       - Code collected in PR 5164 to streamline discussion.
       - We were not happy with some tuning tests.
       - Likewise, many comments left in the source.
       - New type `tuned_model` beneficial?
- [ ] Blowup functions
       - Functions probably could be streamlined? Or improved?
       - Some convenience functions were adapted by FTheoryTools a while back. Do we want them? How?
       - New type `blown_up_model` beneficial?
       - After performing a resolution, all known resolutions should be deleted from the new model, so that they cannot be executed multiple times.
- [ ] For Andrew: https://github.com/oscar-system/Oscar.jl/issues/2522 (only for the concrete models for the time being, see below for steps beyond this).
- [ ] `analyze_fibers(model::GlobalTateModel, centers::Vector{<:Vector{<:Integer}})` is not tested as too expensive. Does it still work? Do we want to add tests to the extra-long tests? Documentation for this function needs massive overhaul as well.
- [ ] Attributes `exceptional_classes` and `exceptional_divisor_indices`: Do not return a default value. Rather, raise error in case we cannot fetch this. In the case at hand, this warning must be "Something is truly wrong in FTheoryTools and needs fixing". And of course, fix these issues as you overhaul this behavior.
- [ ] Ideally attributes and function names should have the same names. This is not the case, not for the QSMs and not for the big model. Updates of the data bases needed to align, but could streamline the code. Not critical and to be discussed if this should at all be on the agenda.
- [ ] New types needed? We have models with
       - Fiber structure is either concrete (said of type I_3) or parametrized (say I_n with n an arbitrary non-negative integer)
       - A concrete base (could either be a toric variety or scheme) or an unspecified base (family of spaces?)       
Questions include but are not limited to:
                  1. What should we call these types?
                  2. Do we need to be clear about what we mean by "family" in "family of spaces"
                  3. Advantage: We could then try to serialize all models in our database in json files.
                  4. Disadvantage: A lot of work.
                  5. Disadvantage 2: We need to first settle the question what a "family of spaces" should be.
- [ ] Mikelis: Found a bug regarding zero sections after blowup? If you can reproduce, ideally fix it. At least provide a MWE.

### G4-fluxes

- [ ] Use flux_coordinates of G4-fluxes to make computations more efficient.
- [ ] Add a method that tells if a flux belong to a flux family.
- [ ] Equality of G4-fluxes is painfully slow. Investigate and improve it
- [ ] Support `is_well_quantized` for flux families with offset.
- [ ] Support `passes_transversality_checks` for flux families with offset.
- [ ] Support `breaks_non_abelian_gauge_group` for flux families with offset.
- [ ] Support `d3_tadpole_constraint` for flux families with offset.
- [ ] Make sure that for all G4-flux operations we can use the sophisticated intersection product.

### Blowup and resolutions

- [ ] We compute strict transforms/pullbacks way too often in our resolution method. Namely, we compute the strict transform of the hypersurface equation after every blowup. Really, we should first execute all blowups, express their combined result in the resulting blowdown morphism and then compute the strict transform along this blowdown morphism - of course, including specialized machinery for the toric case. This is tricky to implement. But my feeling is, that it will give us a HUGE performance boost (e.g. for the BIG model). Try it out!
- [ ] Specific to recently absorbed blow-up methods (cf. https://github.com/oscar-system/Oscar.jl/pull/4528): "One can always improve, for example, explaining exactly what does "cone which corresponds to I" mean, or adding a smoothness test to `_ideal_sheaf_to_minimal_supercone_coordinates` (since smoothness of the toric variety was actually always tested before, I think it would not make the FTheoryTools algorithms slower). But I leave this to you to decide when or whether to do that."
- [ ] Ambient space blowups forget attributes.

### Big model

- [ ] Compute Euler characteristic of big model (= fully resolved, smooth hypersurface).
- [ ] Compute the D3-tadpole for all G4-flux families in this model.
- [ ] Compute all Hodge numbers of the big model (= fully resolved, smooth hypersurface).

### G4-fluxes theory

- [ ] Take a random G4-flux in our big model (or the dual, that Jim is interested in). What is the most likely gauge group left unbroken? Or more precisely, do some statistics that tells us about this.
- [ ] Primitivity condition not yet checked for fluxes: G4 wedge J = 0, J the Kaehler class. Implement this.
- [ ] For remainder flux breaking, the transversality conditions need to be modified (Wati & Kobi).
- [ ] Use advanced algorithm by Braun et all to compute basis of H22 for toric hypersurface. This might have big impact on how we identify families of fluxes. Execute or at least initiate the changes resulting from this.
- [ ] If quantization condition is applied in full, does this imply that the D3-tadpole is automatically integral? (Ling says "this is typically assumed". And about 10 papers seem to believe this statement to be true.)

### New features

- [ ] When defining classes are provided to literature model constructor, the base is implicitly given. Maybe in this case, do not require additional input parameter with base, as this is redundant. Would also improve work flow for users.
- [ ] Decorated and labeled graphs could streamline the QSM data nicely!
- [ ] Use https://docs.oscar-system.org/stable/Groups/action/ for the action of the discrete quotient on the center of the Lie group factors. E.g., the gauge group SU(6)/Z_3 would be stored as the Lie algebra sl(6), then a group action of the quotient factor Z_3 on the center Z_6 of SU(6). Add these to the existing .json files in place of the current specification of the gauge quotients
- [ ] Function `put_over_concrete_base` should work for hypersurface (and complete intersection) models.
- [ ] Convert model over arbitrary base to model over specific base (and vice versa).
- [ ] Add functionality for blowdown morphism.
- [ ] Add support for weighted blowups, thereby absorb the 3 additional blowups for the big model (which only resolve the ambient space).
- [ ] Mordell-Weil group features/consistency checks.

### Family of spaces

- [ ] Improve/enhance family of spaces. We should discuss if abstract varieties (cf. https://docs.oscar-system.org/dev/Experimental/IntersectionTheory/AbstractVarieties/) are to replace family of spaces.
- [ ] Can we have `defining_classes`, `explicit_model_sections` and alike for family of spaces? If so, provide support.

# Long term goals

### Data and serialization

- [ ] Serialize family of basis.
- [ ] Use mrdi files exclusively for model data base, no more json files. (Respectively, keep json only as crutch for model contribution.)
- [ ] Support serialization of G4-flux and G4-flux family.
- [ ] Provide metadata and metadata querries via the Mardi portal.

### New models for data base

- [ ] Support complete intersection models.
- [ ] Add model that Jim interested in: See https://arxiv.org/pdf/hep-th/9704097v2, section 4.5. We wants the model of the DUAL polytope, with h11 = 303148, h31 = 252.
- [ ] Put in the model https://arxiv.org/pdf/2210.09473.pdf, to test Weierstrass model resolution. Equ. 3.10 resolves in Weierstrass form. Equ. 3.11 involves a messy locus and thus valuable test to gauge our computational state of affairs.
- [ ] Nikhil & Andrew model and Mordell-Weil -> Future avenue and to be supported in the `FTheoryTools`. (And paper to be released eventually).
- [ ] CKPT (https://arxiv.org/abs/1507.05954)
- [ ] Raghuram charge 3 and 4 (https://arxiv.org/abs/1711.03210) (cf. #4155)
- [ ] Exotic Matter (https://arxiv.org/abs/1706.08194)
  - [ ] Matter in Transition (https://arxiv.org/abs/1512.05791)
  - [ ] These models may require new technology for us
- [ ] Generic SM models (https://arxiv.org/abs/1912.10991)
  - [ ] Related to QSMs
  - [ ] Also (https://arxiv.org/abs/2210.09473), which is also above
- [ ] Tate with MW rank 1 (https://arxiv.org/abs/1406.5174)
- [ ] Matter and Singularities (https://arxiv.org/abs/1106.3563), maybe
- [ ] Highest MW rank (https://arxiv.org/abs/2105.02863)
- [ ] Include the model by Wati and Kobe (https://arxiv.org/pdf/2401.00040.pdf).

### QSM focus

- [ ] Expect matter at curves between different `U(2)` factors, that is not charged under `U(1)`. Add technology for these computations into `FTheoryTools`. (Andrew)
- [ ] Present the `blow_ups` (in particular if conducted on affine charts) in a way that is readable for physicists. Also interpret complicated blowups. To be discussed with Anne. (Andrew)
- [ ] Some level of support for chiral spectra. (Martin)
- [ ] Study singular limit of `QSMs` (c.f. root bundles papers) and try to resolve the singular geometry.
- [ ] Keep track of U(1) sections. (Yes, their resolution is at another level, but we should be able to keep track of them.)

### Milestones

- [ ] Tate autoresolver: Use insights of "Tateform on steroids" to automatically resolve a Tate model as much as possible. (Andrew)
- [ ] Migrate the code from experimental into source.
- [ ] Nagell's algorithm?

# Completed

- [x] Nicer formatting of the code and checking the format in future PRs (https://github.com/oscar-system/Oscar.jl/pull/5309)
- [x] Check for more uses of random (random flux instance for instance) and adjust accordingly. (https://github.com/oscar-system/Oscar.jl/pull/5295)
- [x] Toric geometry - generic section - make it less random (https://github.com/oscar-system/Oscar.jl/pull/5278)
- [x] Reduce allocations (cf. https://github.com/oscar-system/Oscar.jl/pull/4928).
- [x] Remove some unused functionality (https://github.com/oscar-system/Oscar.jl/pull/5269)
- [x] More updates on resolution structure (https://github.com/oscar-system/Oscar.jl/pull/5268)
- [x] Minor kwarg change (https://github.com/oscar-system/Oscar.jl/pull/5263).
- [x] In the documentation, the keyword "check" is sometimes stated in doc string of some methods and sometimes it is not. And sometimes it is not clearly stated what it does... See also the point about streamlining these optional arguments further below. (https://github.com/oscar-system/Oscar.jl/pull/5214)
- [x] Streamline naming convention for optional arguments (check vs. quick vs. ...) (https://github.com/oscar-system/Oscar.jl/pull/5214)
- [x] Prepare changing the names of kwargs by addressing their toric counterparts (https://github.com/oscar-system/Oscar.jl/pull/5234).
- [x] Add a brief word of resolution data types. Also, add a brief word on weighted blowups. (https://github.com/oscar-system/Oscar.jl/pull/5254)
- [x] Reduce code duplication in serialization of Tate, Weierstrass and hypersurface models (https://github.com/oscar-system/Oscar.jl/pull/5222).
- [x] Add all code used in our paper to the OSCAR CI tests, so that we’re alerted if future code changes break the examples. (https://github.com/oscar-system/Oscar.jl/pull/5205)
- [x] Optimize test files. (https://github.com/oscar-system/Oscar.jl/pull/5205)
- [x] A family of spaces should not support Cox ring. Rather, let us use `coordinate_ring` (alias for `cox_ring`) of a toric variety. (https://github.com/oscar-system/Oscar.jl/pull/5200)
- [x] Verbosity printing: Suppress the output by default. (https://github.com/oscar-system/Oscar.jl/pull/5170)
- [x] Overhaul structure of the source code (https://github.com/oscar-system/Oscar.jl/pull/5164).
- [x] `calabi_yau_hypersurface` should be an attribute of `AbstractFTheoryModel` (https://github.com/oscar-system/Oscar.jl/pull/5164).
- [x] Overhaul adder functions with more structure, doc tests and more efficient code. (https://github.com/oscar-system/Oscar.jl/pull/5161).
- [x] Move on with https://github.com/oscar-system/Oscar.jl/issues/4593. (https://github.com/oscar-system/Oscar.jl/pull/5156)
- [x] Explain later parts of the documentation better. This is currently just a rough summary of what functions belong together. (https://github.com/oscar-system/Oscar.jl/pull/5160)
- [x] Streamline doctests. (https://github.com/oscar-system/Oscar.jl/pull/5160)
- [x] Move Kbar3 from QSMs to the topology section, as applies generally. Link to it from the QSM page. (https://github.com/oscar-system/Oscar.jl/pull/5159)
- [x] Restructure docu on generalities. (https://github.com/oscar-system/Oscar.jl/pull/5154)
- [x] Overhaul QSM docu (https://github.com/oscar-system/Oscar.jl/pull/5148)
- [x] Dedicated page for QSM models. (https://github.com/oscar-system/Oscar.jl/pull/5147)
- [x] Move generating sections and alike to generalities, i.e. out of literature model page. (https://github.com/oscar-system/Oscar.jl/pull/5147)
- [x] Extend macro to accept customized link to dedicated section in the documentation. (https://github.com/oscar-system/Oscar.jl/pull/5147)
- [x] The .json files for the literature models use "model_sections" to refer to every named section introduced in the model. This does *not* include parametrized sections, which don't appear explicitly in the model definition, so this is essentially a synonym for "tunable_sections" that is used only in the .json files and, as a result, the literature model constructors. This should be fixed in future. (https://github.com/oscar-system/Oscar.jl/pull/5146)
- [x] Make links more stable using an @ id (https://github.com/oscar-system/Oscar.jl/pull/5146)
- [x] Add back # Examples to our doc strings and enforce imperative in doc strings (rename `Returns` to `Return`, etc.) (https://github.com/oscar-system/Oscar.jl/pull/5145)
- [x] General code styling of the literature model and other documentation pages needed. (https://github.com/oscar-system/Oscar.jl/pull/5083)
 - [x] `Hypersurface_equation_parametrization` (of hypersurface model) has a doc string that also uses literature model constructor, but literature models have not been introduced. Move to a later section of the documentation. (https://github.com/oscar-system/Oscar.jl/pull/5083)
- [x] Meaning of resolution_zero_sections, resolution_generating_section to be clarified. Why do we have as many as we seem to have? Why do some of them have fewer coordinates than others? (https://github.com/oscar-system/Oscar.jl/pull/5083)
- [x] Take notice that I removed `sample_toric_variety()`.
- [x] Take notice that I removed `weierstrass_model(w::WeierstrassModel)`.
- [x] Take notice that I removed `su5_weierstrass_model_over_arbitrary_3d_base`.
- [x] Take notice that I removed `su5_tate_model_over_arbitrary_3d_base`.
- [x] Take notice of the extended flexibility in hypersurface model constructors: the twists need no long go into the first two fiber coordinates.
- [x] Take notice of the changes in https://github.com/oscar-system/Oscar.jl/pull/5083 (new function `add_torsion_section`, `cox_ring` of family of spaces is now graded, streamlined some of the nested data types a bit better, use macro to define some of the standard attribute getters - this could likely be extended to be used much wider in FTheoryTools).
- [x] Is the explanation complete? For instance, have we ever carefully defined the datum/defining data of an F-Theory model? Does this include the model sections? (https://github.com/oscar-system/Oscar.jl/pull/5071)
- [x] `HypersurfaceModels/Constructors.jl` needs updating. For instance `D1` etc. are probably to be removed/explained better. (https://github.com/oscar-system/Oscar.jl/pull/5071)
- [x] Tune methods use literature model constructors, but appear before literature models are discussed. Discuss those methods on another page. (https://github.com/oscar-system/Oscar.jl/pull/5071)
- [x] Do doc strings explain general setups again and again for G4-fluxes? If so, remove duplication of content. (cf. https://github.com/oscar-system/Oscar.jl/pull/5048)
- [x] Remove `su5_weierstrass_model_over_arbitrary_3d_base` and `su5_tate_model_over_arbitrary_3d_base`. They are stated as literature_models in the current documentation, which is way outdated. Also, we did already remove those functions from being exported, but still used them in some examples. Not at all good. (cf. https://github.com/oscar-system/Oscar.jl/pull/5048)
- [x] Compute integral and rational coefficients of every G4-flux and remember this. (cf. https://github.com/oscar-system/Oscar.jl/pull/5031)
- [x] G4-fluxes can be converted into the basis chosen internally by FTheoryTools. Enhance/improve. Maybe make this our standard, so that this always happens. (cf. https://github.com/oscar-system/Oscar.jl/pull/5031)
- [x] Hard code that ambient space and base space of any QSM model are complete (and smooth and simplicial). (https://github.com/oscar-system/Oscar.jl/pull/5019)
- [x] Chern classes cannot be serialized - cast them as dict, then the serialization should (hopefully) work. Alternatively, employ a vector of tuples. (https://github.com/oscar-system/Oscar.jl/pull/5017)
- [x] Carefully scan for incorrect uses of lifting a polynomial from a quotient ring to the base ring. (https://github.com/oscar-system/Oscar.jl/pull/5016)
- [x] Why is it called quotientS and not quotient? Do we expect multiple gauge group quotient structures to exist in one geometry? Rename to global gauge group quotient? (https://github.com/oscar-system/Oscar.jl/pull/4876)
- [x] Printing of a vector of torus invariant prime divisors is suuuuuuuper slow. Printing a single torus invariant prime divisor is fast. Why is that? And fix it of course! (https://github.com/oscar-system/Oscar.jl/pull/4846)
- [x] Cohomology class constructor is slow. Thus far, we circumvented it. Time to improve it fundamentally. (https://github.com/oscar-system/Oscar.jl/pull/4846)
- [x] Overhaul introduction and big picture of G4-flux documentation (https://github.com/oscar-system/Oscar.jl/pull/5009)
- [x] Book chapter and good names for wrapper functions
- [x] Toric schemes (see https://github.com/oscar-system/Oscar.jl/pull/2700)
- [x] Uniform `blow_up` code among toric and scheme settings (cf. https://github.com/oscar-system/Oscar.jl/pull/2741).
- [x] Add function `blow_up` (or `resolve`) that accepts an F-theory model and blows it up/resolves it. (https://github.com/oscar-system/Oscar.jl/pull/3012)
- [x] Do we need new "types" for partially or fully-resolved models? Answer: No.
- [x] Add function `tune`, that allows to set parameters to specialized choice (-> add singularity/enlarge gauge group). (Cf. https://github.com/oscar-system/Oscar.jl/pull/3146)
- [x] Complicated centers can be blown up with the schemes technology. However, this is currently only possible for smooth toric varieties. This in turn is the case because we can create ideal sheaves only for such toric varieties. Extended in https://github.com/oscar-system/Oscar.jl/pull/3513.
- [x] Support non-toric blowups and update `_construct_literature_model_over_concrete_base` and the documentation of `put_over_concrete_base` to use generic sections.  (Cf. https://github.com/oscar-system/Oscar.jl/pull/3519)
- [x] Tuning must work for setting sections to zero. (Cf. https://github.com/oscar-system/Oscar.jl/pull/3726)
- [x] Use (https://docs.oscar-system.org/stable/Experimental/LieAlgebras/lie_algebras/) for the Lie algebras (cf. https://github.com/oscar-system/Oscar.jl/pull/3822, https://github.com/oscar-system/Oscar.jl/pull/3908)
- [x] Extend the tutorial: https://www.oscar-system.org/tutorials/FTheoryTools/
- [x] Use Matthias' proper transformation function when possible/needed.
- [x] Limit coefficients in generic sections (cf. https://github.com/oscar-system/Oscar.jl/pull/3930)
- [x] Provide serialization support for toric divisor classes (cf. https://github.com/oscar-system/Oscar.jl/pull/3931)
- [x] Added F-theory models on all toric hypersurfaces (https://arxiv.org/abs/1408.4808v1): https://github.com/oscar-system/Oscar.jl/pull/3568
- [x] More models from "F-theory on all toric hypersurfaces": https://github.com/oscar-system/Oscar.jl/pull/3642
- [x] Clarify and improve mechanics of literature model constructor: https://github.com/oscar-system/Oscar.jl/pull/3675
- [x] Reparametrized literature models in "F-theory on all toric hypersurfaces": https://github.com/oscar-system/Oscar.jl/pull/3693
- [x] Updates to hypersurface model constructor: https://github.com/oscar-system/Oscar.jl/pull/3699
- [x] Various improvements: https://github.com/oscar-system/Oscar.jl/pull/3712
- [x] https://github.com/oscar-system/Oscar.jl/pull/3424 (see also https://github.com/oscar-system/Oscar.jl/pull/3506)
- [x] Support more than just {w = 0} as gauge divisor for calculation of singular loci (cf. #3718)
- [x] Basic support the `QSMs` as literature models. (https://github.com/oscar-system/Oscar.jl/pull/3363)
- [x] Refactoring of the QSMs, so that attributes are better available (https://github.com/oscar-system/Oscar.jl/pull/3871)
- [x] Add comments in code that fully explain defining_classes, explicit_model_sections, etc. (https://github.com/oscar-system/Oscar.jl/pull/4597)
- [x] Update attribute that associates a Weierstrass model to a hypersurface/Tate model, so that it can construct the WS model associated to a given model from the database when another database file exists for it.
- [x] Update serialization and first steps towards database 2.0 (cf. https://github.com/oscar-system/Oscar.jl/pull/3932, https://github.com/oscar-system/Oscar.jl/pull/4620)
- [x] Based on https://github.com/oscar-system/Oscar.jl/pull/3980, could also serialize Lie algebras of the FTheoryModels. Again, a particular instance includes the QSM models.
- [x] Add an artifact/database or alike for the model discussed in https://github.com/oscar-system/Oscar.jl/pull/3978. I have the corresponding .mrdi files and will be happy to share them. They are about 1.5TB in total size.)
- [x] Make use of the attribute saver of @antonydellavecchia (cf. https://github.com/oscar-system/Oscar.jl/pull/4020) to automatically serialize more/all attributes. For instance, even after the above, for instance the known resolutions are not saved for FTheory models. (Will happen via https://github.com/oscar-system/Oscar.jl/pull/4162)
- [x] Typo in F11 model zero section to be fixed (cf. https://github.com/oscar-system/Oscar.jl/pull/4717).
- [x] Convenience methods for creating flux families (cf. https://github.com/oscar-system/Oscar.jl/pull/4711).
- [x] Investigate why loading of FTheoryTools big model takes sooo long on computer of @HereAround. (Fixed by upgrading to julia 1.11 on March 31).
- [x] Extend flux family computations to include c2/2 (cf. https://github.com/oscar-system/Oscar.jl/pull/4728).
- [x] Computation of c2 is never terminating for the big model. Investigate and improve/speed it up. (Part of cf. https://github.com/oscar-system/Oscar.jl/pull/4728).
- [x] Improve the code for computation of family of G4-fluxes. (At least some steps in #4728 - beyond that improvements are always possible of course)
- [x] Why does calling converter_dict on the same model twice - by this I mean building this again from serialization - lead to empty entries in that converter dict?!? Fix this!(Fixed in #4728)
- [x] Steps for recreating the super dupa mega big bigger model. (Added to overleaf and slack).
- [x] Add converter dict tests to CIs that run with every commit/push. (cf. https://github.com/oscar-system/Oscar.jl/pull/4784)
- [x] Index of exceptional divisors should be attribute, rather than trying to match string case (in special_flux). This is also rather fragile (fixed by https://github.com/oscar-system/Oscar.jl/pull/4779)
- [x] tunable_section setting does not work in literature model constructor for the big model. Investigate. (fixed by https://github.com/oscar-system/Oscar.jl/pull/4779)
- [x] Speed of exceptional divisors, ideally resolve employs this once only. And then, the fast version to create a cohomology class. (fixed by https://github.com/oscar-system/Oscar.jl/pull/4779)
- [x] Add the exceptional divisor indices for big model. (https://github.com/oscar-system/Oscar.jl/pull/4843)
- [x] Zenodo: Only save the .zip file of big odel (otherwise, confuse people? also saves space and download time). (Completed with https://github.com/oscar-system/Oscar.jl/pull/4843).
- [x] Improve and verify newly computed big model data. (https://github.com/oscar-system/Oscar.jl/pull/4803)
- [x] Fix the paper buzzwords for big model (not SU(5) GUT model, but rather "the F-theory geometry with the largest number of flux vacua?") (https://github.com/oscar-system/Oscar.jl/pull/4844)
- [x] Do we want the steps to recreate the very big model from scratch to be somewhere in the OSCAR code base? Or include this in our tutorial? (https://github.com/oscar-system/Oscar.jl/pull/4844)
- [x] Add more tests for big model (https://github.com/oscar-system/Oscar.jl/pull/4844)
- [x] Update printing of fluxes and families of fluxes. (https://github.com/oscar-system/Oscar.jl/pull/4844)
- [x] Adjust printing of all F-theory tools objects (detailed, terse, one-line) (https://github.com/oscar-system/Oscar.jl/pull/4844)
- [x] Once serialization overhaul is complete: Overhaul the QSMs. Important fields are not set, such as tunable sections, explicit model sections and alike. Serialize the special G4-flux chosen for the QSMs (cf. https://arxiv.org/pdf/2102.10115, equ. **2.25). Once complete, create .mrdi file for every QSM, zip them and upload them to https://github.com/oscar-system/Oscar.jl/releases/tag/archive-tag-1. (This upload may only be possible for @HereAround , but of course someone else could create the files.) Important: Do *not* delete the old version, but rather add a new version. Finally, inform OSCAR on the updated artifact (cf. https://pkgdocs.julialang.org/v1/artifacts/). (https://github.com/oscar-system/Oscar.jl/pull/4869)
- [x] Add exceptional divisor indicies and classes for the QSMs. (https://github.com/oscar-system/Oscar.jl/pull/4869)
- [x] Supply other missing information for QSM models (say explicit model sections). (https://github.com/oscar-system/Oscar.jl/pull/4869)
- [x] Once serialization overhaul is complete, make timings for loading of files and compare with loading before the serialization overhaul. This seems to depend a lot on the OS and hardware used. The gauge for @HereAround 's system is, that the loading is slower. If indeed true, investigate a bit. (Is it only a bit slower or a lot? If just a bit - ignore. Otherwise, see if there are way to speed up the loading...). Solution was to update to julia 1.11 on @HereAround system.

# Abandoned for now

- Convert a Weierstrass into a Tate model? Can be done locally, but what is the global obstruction? Let us not (yet) get into this.
- Investigate and strengthen connection to PolyDB? Maybe give some words of explanation in the documentation? In particular, 3d KS-database should (but currently does not to my knowledge) exist in PolyDB and we could access and use that in OSCAR/FTheoryTools.
- Make computation of Tate sections lazy to gain speed-up on construction?
