### ISSUE TITLE
Schemes Meta Issue

### ISSUE THREAD

**Issue by simonbrandhorst** [oscar-system/Oscar.jl#3202]
This is a todo list for the schemes part of OSCAR

- [x] implement `defining_ideal(::AbsSpec)`. In case of a closed subscheme of AA^n it should return an ideal in the corresponding polynomial ring, in case of a closed subscheme of some open subscheme  U of AA^n it should return an ideal in `OO(U)` https://github.com/oscar-system/Oscar.jl/pull/3205
- [x] rename `Spec` to `AffineScheme` https://github.com/oscar-system/Oscar.jl/issues/3345
- [x] change one line printing of closed subschemes of `AA^n` from `V(...)` to `scheme(...)`
- [x] rename `issubset` for (affine & projective) schemes to `is_subscheme` and implement `issubset` 
- [x] migrate ideal sheaves and divisors to src
- [ ] implement weighted projective space including `is_quasi_smooth` 
@jankoboehm @HechtiDerLachs @afkafkafk13 @paemurru 
- [x] implement normalisation for affine schemes
- [x] implement normalisation for covered schemes
- [x] desungularisation for (covered) surfaces via blowup and normalisation
- [ ] check if the singular code for invert_birational_map works more generally and adapt it. Remove the duplicate for plane curves.

**Comment by HechtiDerLachs** [comment]
Let me try to do the `defining_ideal` thing today.

**Comment by fingolfin** [comment]
What's the status of this?

**Comment by simonbrandhorst** [comment]
Some progress, updated.

**Comment by paemurru** [comment]
About weighted projective spaces and `is_quasi_smooth` - weighted projective spaces already exist as toric varieties. Quasismoothness test should then be implemented more generally for subschemes in toric varieties. So I think it is more about toric varieties and can be removed from here.
