### ISSUE TITLE
flint 3 update roadmap

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#3652]
We are slowly converging to a point, where we could/should update to flint 3. We already have PRs adjusting Nemo and Hecke. They just need to be merged:
- [ ] Adjust Nemo.jl (https://github.com/Nemocas/Nemo.jl/pull/1568)
- [ ] Adjust Hecke.jl (https://github.com/thofma/Hecke.jl/pull/1475)
- [ ] Adjust Singular.jl (https://github.com/oscar-system/Singular.jl/pull/801)

I think what remains to do is
- [x] rebuild binaries for Singular (https://github.com/JuliaPackaging/Yggdrasil/pull/8546)
- [x] rebuild binaries for normaliz (https://github.com/JuliaPackaging/Yggdrasil/pull/8541)
- [x] rebuild binaries for polymake (https://github.com/JuliaPackaging/Yggdrasil/pull/8545)
- [x] rebuild binaries for libsingular_julia (https://github.com/JuliaPackaging/Yggdrasil/pull/8579)
- [x] rebuild binaries for libpolymake_julia (https://github.com/JuliaPackaging/Yggdrasil/pull/8578)
- [x] rebuild binaries for polymake_oscarnumber

I think rebuilding the binaries would be the next logical step.

I hope I did not miss anything. Comments and corrections welcome.

CC: @benlorenz @fingolfin

**Comment by thofma** [comment]
I think we have everything now in place. But I want to wait till https://github.com/oscar-system/Oscar.jl/pull/3667 is merged.

**Comment by thofma** [comment]
#3689
