### ISSUE TITLE
Toric Varieties: Completed goals from fall 2021 until December 2022

### ISSUE THREAD

**Issue by HereAround** [oscar-system/Oscar.jl#763]
The following is a list of tasks that were completed on toric varieties between fall of 2021 and December 2022. A follow-up for 2023 is available at https://github.com/oscar-system/Oscar.jl/issues/1834.

###############################################################################
###############################################################################
**Completed**:
###############################################################################
###############################################################################

- [x] Compute intersections in the Chow ring (cf. https://github.com/oscar-system/Oscar.jl/pull/1449).
- [x] Group of Cartier torus invariant divisors (cf. https://github.com/oscar-system/Oscar.jl/pull/820)
- [x] Cache computed properties (see https://github.com/oscar-system/Oscar.jl/pull/839)
- [x] More sophisticated show methods for toric varieties and toric divisors (see https://github.com/oscar-system/Oscar.jl/pull/839)
- [x] Picard group (done in https://github.com/oscar-system/Oscar.jl/pull/820),
- [x] Allow the user to choose names for the coordinates in the Cox ring. (For example, I would like to label homogeneous coordinates introduced by a blowup by `e`.) (https://github.com/oscar-system/Oscar.jl/issues/932 and https://github.com/oscar-system/Oscar.jl/pull/939.)
- [x] line bundle cohomologies via cohomCalg (https://github.com/oscar-system/Oscar.jl/pull/944).
- [x] Structure sheaf of toric varieties (https://github.com/oscar-system/Oscar.jl/pull/1032).
- [x] Coordinate ring of torus (https://github.com/oscar-system/Oscar.jl/pull/1115)
- [x] List of variables of coordinate ring of torus (https://github.com/oscar-system/Oscar.jl/pull/1115)
- [x] The rational function of a character (https://github.com/oscar-system/Oscar.jl/pull/1115)
- [x] Construct toric varieties from all triangulations (likely via topcom). First step done in https://github.com/oscar-system/Oscar.jl/pull/848, see also https://github.com/oscar-system/Oscar.jl/pull/1115.
- [x] Construct toric varieties from GLSM charges (https://github.com/oscar-system/Oscar.jl/pull/1115).
- [x] global sections of toric line bundle from monoms of the Cox ring of a certain multidegree (https://github.com/oscar-system/Oscar.jl/pull/1115).
- [x] canonical bundle (https://github.com/oscar-system/Oscar.jl/pull/1209)
- [x] anti-canonical bundle (https://github.com/oscar-system/Oscar.jl/pull/1209)
- [x] (anti)canonical divisor (https://github.com/oscar-system/Oscar.jl/pull/1146)
- [x] (anti) canonical divisor class (https://github.com/oscar-system/Oscar.jl/pull/1146)
- [x] trivial divisor (class) (https://github.com/oscar-system/Oscar.jl/pull/1146)
- [x] Volume form (https://github.com/oscar-system/Oscar.jl/pull/1146).
- [x] Intersection form (https://github.com/oscar-system/Oscar.jl/pull/1146).
- [x] Compute topological intersection numbers (https://github.com/oscar-system/Oscar.jl/pull/1146).
- [x] Chow ring (cf. https://github.com/oscar-system/Oscar.jl/pull/1146).
- [x] Cohomology ring (cf. https://github.com/oscar-system/Oscar.jl/pull/1146).
- [x] Fix weights of Cox ring for del Pezzo and Hirzebruch surface to a standard choice. (https://github.com/oscar-system/Oscar.jl/pull/1146)
- [x] use cohomCalg to identify vanishing sets (key for many algorithms in https://github.com/homalg-project/ToricVarieties_project): https://github.com/oscar-system/Oscar.jl/pull/1236
- [x] Toric morphisms (cf. https://github.com/oscar-system/Oscar.jl/pull/1460).
- [x] Support Cox variety (cf. https://github.com/oscar-system/Oscar.jl/pull/1460).
- [x] Rays are being shuffled. Provide additional argument for all constructors of toric varieties to switch this off if desired. (cf. https://github.com/oscar-system/Oscar.jl/issues/1208 and https://github.com/oscar-system/Oscar.jl/issues/1258 and https://github.com/oscar-system/Oscar.jl/pull/1676).
- [x] Marry the different implementation of the Cow ring (cf. https://github.com/oscar-system/Oscar.jl/issues/1475 and https://github.com/oscar-system/Oscar.jl/pull/1650, https://github.com/oscar-system/Oscar.jl/pull/1684).
- [x] Compute induced map among class groups and Picard groups (cf. https://github.com/oscar-system/Oscar.jl/pull/1770).
- [x] Variable names (of homogeneous coordinates) for direct products: Default: prepend x and y. Optionally allow to pass list with variable names. (cf. https://github.com/oscar-system/Oscar.jl/pull/1815)

###############################################################################
###############################################################################
**Abandoned**:
###############################################################################
###############################################################################

- Remember all toric divisors created for a toric variety.
- Remember genesis of a toric variety, e.g. if it was obtained as direct product and if so, apply refined algorithms.
- Support polymake's CARTIER_DATA.
